### PR TITLE
Changed the URL for lightning example

### PR DESCRIPTION
**Pull request by JiapengWu**

### CODE REVIEW

**Comment by benedekrozemberczki** [comment]
Thank you for catching this!

**Comment by JiapengWu** [comment]
No problem! Also, can I ask you which version of pytorch lightning are you using in the example?


On Jul 2, 2021, at 12:39 PM, Benedek Rozemberczki ***@***.******@***.***>> wrote:



Thank you for catching this!

**Comment by benedekrozemberczki** [comment]
pytorch-lightning==1.3.0

May I ask what are you planning to do with the library?

Bests,

Benedek

**Comment by JiapengWu** [comment]
Thanks Benedek, I am experimenting with some input decomposition methods and I want to see if they work well with the spatiotemporal forecasting models.

Best,

Paul

On Jul 2, 2021, at 12:44 PM, Benedek Rozemberczki ***@***.******@***.***>> wrote:



pytorch-lightning==1.3.0

May I ask what are you planning to do with the library?

Bests,

Benedek

**Pull request merged**
