### PR TITLE
Evolvegcno: enable recurrent weights to be updated in both O and H versions and update example

### PR DESCRIPTION
**Pull request by SherylHYX**
As mentioned in https://github.com/benedekrozemberczki/pytorch_geometric_temporal/issues/80, this PR is to resolve the problem of updating the weights. Several major points:

1) Change the LSTM into GRU for EvolveGCNO based on  https://github.com/IBM/EvolveGCN/blob/90869062bbc98d56935e3d92e1d9b1b4c25be593/egcn_o.py#L77

2) Set initial convolution weights to be trainable but later to be updated only via RNN.

3) Rewrite the GCNConv class so that only message passing structure is used but the weights are not trainable inside GCN.

4) One thing to note, a difference from the original implementation from IBM: the bias in the original implementation is a matrix while in GRU/LSTM bias is a vector. Therefore, for the example given, the number of recurrent parameters inside the EvolveGCNO class is 449=144 for the original implementation while that is 1210=120 for GRU and 1610=160 for LSTM.

### CODE REVIEW

**Comment by benedekrozemberczki** [comment]
Dear @SherylHYX,

The build is failing. Could you look into this?

Bests,

Benedek

**Comment by SherylHYX** [comment]
Yes, I will, perhaps in a few days.
________________________________

**Comment by benedekrozemberczki** [comment]
@SherylHYX the test coverage has decreased. Can you take a look why?

**Comment by SherylHYX** [comment]
> @SherylHYX the test coverage has decreased. Can you take a look why?

Because I have modified the code for GCNConv and have not yet written tests for that. I will update soon.

**Pull request merged**
