### PR TITLE
added mtm1-dataset

### PR DESCRIPTION
**Pull request by alexriedel1**
Hi,
I added a dataset of 3D hand keypoint motion data for classifying gestures used in industrial production https://en.wikipedia.org/wiki/Methods-time_measurement

### CODE REVIEW

**Comment by benedekrozemberczki** [comment]
Dear Alex,  Can you modify the paper?

**Comment by benedekrozemberczki** [comment]
(Add a line in the paper in the datasets table and a paragraph about the dataset.)

**Comment by alexriedel1** [comment]
> (Add a line in the paper in the datasets table and a paragraph about the dataset.)

done.

**Comment by benedekrozemberczki** [comment]
Merged it.

**Pull request merged**
